CREATE DATABASE QLThuoc
GO
use QLThuoc
GO
CREATE TABLE DangThuoc(
MaDangThuoc VARCHAR(10) PRIMARY KEY,
TenDangThuoc NVARCHAR(50))
GO
CREATE TABLE LoaiThuoc(
MaLoaiThuoc VARCHAR(10) PRIMARY KEY,
TenLoaiThuoc NVARCHAR(50),
MaDangThuoc VARCHAR(10) REFERENCES dbo.DangThuoc(MaDangThuoc))
GO
CREATE TABLE NhaCungCap(
MaNCC VARCHAR(10) PRIMARY KEY,
TenNCC NVARCHAR(50),
SDT VARCHAR(11),
DiaChi NVARCHAR(100))
GO
CREATE TABLE CoSo(
MaCS VARCHAR(10) PRIMARY KEY,
TenCS NVARCHAR(50),
DiaChi NVARCHAR(50),
SDT VARCHAR(11))
GO
CREATE TABLE NhanVien(
MaNV VARCHAR(10) PRIMARY KEY,
TenNV NVARCHAR(50),
MaCS VARCHAR(10) REFERENCES dbo.CoSo(MaCS),
SDT VARCHAR(11),
DiaChi NVARCHAR(50))
GO
CREATE TABLE KhachHang(
MaKH VARCHAR(10) PRIMARY KEY,
TenKH NVARCHAR(50),
DiaChi NVARCHAR(50),
SDT VARCHAR(11),
CongNo BIGINT)
GO
CREATE TABLE Thuoc(
MaThuoc VARCHAR(10) PRIMARY KEY,
TenThuoc NVARCHAR(50),
MaLoaiThuoc VARCHAR(10) REFERENCES dbo.LoaiThuoc(MaLoaiThuoc),
MaDVSX VARCHAR(10) REFERENCES dbo.NhaCungCap(MaNCC),
CongDung NVARCHAR(100),
HSD NVARCHAR(50),
SoLuong INT,
NuocSX NVARCHAR(50))
GO
CREATE TABLE HoaDonXuat(
MaHoaDon VARCHAR(10) PRIMARY KEY,
MaKH VARCHAR(10) REFERENCES dbo.KhachHang(MaKH),
MaThuoc VARCHAR(10) REFERENCES dbo.Thuoc(MaThuoc),
DonViTinh NVARCHAR(50),
SoLuong INT,
GiaXuat BIGINT,
NgayXuat DATE,
MaNVXuat VARCHAR(10),
ThanhTien BIGINT,
DaThanhToan BIGINT,
ConNo BIGINT)
GO
CREATE TABLE HoaDonNhap(
MaHoaDon VARCHAR(10) PRIMARY KEY,
MaNCC VARCHAR(10) REFERENCES dbo.NhaCungCap(MaNCC),
MaThuoc VARCHAR(10) REFERENCES dbo.Thuoc(MaThuoc),
DonViTinh NVARCHAR(50),
SoLuong INT,
GiaNhap BIGINT,
NgayNhap DATE,
MaNVNhap VARCHAR(10) REFERENCES dbo.NhanVien (MaNV),
ThanhTien BIGINT,
DaThanhToan BIGINT,
ConNo BIGINT)
GO

GO
USE QLGV_HS_THPT

GO

CREATE PROC xoaHS(@MaHS VARCHAR(10))
AS
BEGIN
	DELETE dbo.HocSinh WHERE MaHS=@MaHS
END
