DROP DATABASE QLThuoc
go
CREATE DATABASE QLThuoc
GO
use QLThuoc

GO
CREATE TABLE LoaiThuoc(
MaLoaiThuoc VARCHAR(10) PRIMARY KEY,
TenLoaiThuoc NVARCHAR(50),
GhiChu NVARCHAR(100))
GO
CREATE TABLE NhaCungCap(
MaNCC VARCHAR(10) PRIMARY KEY,
TenNCC NVARCHAR(50),
SDT VARCHAR(11),
DiaChi NVARCHAR(100))
GO
CREATE TABLE CoSo(
MaCS VARCHAR(10) PRIMARY KEY,
TenCS NVARCHAR(50),
DiaChi NVARCHAR(50),
SDT VARCHAR(11))
GO
CREATE TABLE NhanVien(
MaNV VARCHAR(10) PRIMARY KEY,
TenNV NVARCHAR(50),
MaCS VARCHAR(10) REFERENCES dbo.CoSo(MaCS),
GioiTinh bit,
NgaySinh DATE,
SDT VARCHAR(11),
DiaChi NVARCHAR(50))
GO
CREATE TABLE KhachHang(
MaKH VARCHAR(10) PRIMARY KEY,
TenKH NVARCHAR(50),
DiaChi NVARCHAR(50),
SDT VARCHAR(11))
GO
CREATE TABLE Thuoc(
MaThuoc VARCHAR(10) PRIMARY KEY,
TenThuoc NVARCHAR(50),
MaLoaiThuoc VARCHAR(10) REFERENCES dbo.LoaiThuoc(MaLoaiThuoc),
MaDVSX VARCHAR(10) REFERENCES dbo.NhaCungCap(MaNCC),
CongDung NVARCHAR(100),
HSD NVARCHAR(50),
SoLuong INT,
NuocSX NVARCHAR(50))
GO
CREATE TABLE ChiTietHoaDonXuat(
MaCTHDX VARCHAR(10) PRIMARY KEY,
MaThuoc VARCHAR(10) REFERENCES dbo.Thuoc(MaThuoc),
DonViTinh NVARCHAR(50),
Gia BIGINT,
SoLuong INT)
GO
CREATE TABLE HoaDonXuat(
MaHoaDon VARCHAR(10) PRIMARY KEY,
MaCTHDX VARCHAR(10) REFERENCES dbo.ChiTietHoaDonXuat(MaCTHDX),
MaKH VARCHAR(10) REFERENCES dbo.KhachHang(MaKH),
NgayXuat DATE,
MaNVXuat VARCHAR(10),
ThanhTien BIGINT)
GO
CREATE TABLE ChiTietHoaDonNhap(
MaCTHDN VARCHAR(10) PRIMARY KEY,
MaThuoc VARCHAR(10) REFERENCES dbo.Thuoc(MaThuoc),
DonViTinh NVARCHAR(50),
Gia BIGINT,
SoLuong INT)
GO
CREATE TABLE HoaDonNhap(
MaHoaDon VARCHAR(10) PRIMARY KEY,
MaNCC VARCHAR(10) REFERENCES dbo.NhaCungCap(MaNCC),
MaCTHDN VARCHAR(10) REFERENCES dbo.ChiTietHoaDonNhap(MaCTHDN),
NgayNhap DATE,
MaNVNhap VARCHAR(10) REFERENCES dbo.NhanVien (MaNV),
ThanhTien BIGINT)



